# Generated by Django 2.1.3 on 2018-11-07 20:25

from django.db import migrations, models
import storage.myfunctions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_obj', models.CharField(default='', max_length=32, verbose_name='Введите хэш удаляемого файла')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_obj', models.CharField(default='', max_length=32, verbose_name='Введите хэш файла для скачивания')),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(upload_to=storage.myfunctions.hash_upload, verbose_name='Загрузка файла')),
            ],
        ),
    ]
